---
title: Smit Shah
timezone: Asia/Colombo
collections:
  posts:
    title: Posts
    output: true
    permalink: pretty
  project:
    title: Projects
    output: true
    permalink: pretty
  uploads:
    title: Uploads
    output: true
email: smitshah81@gmail.com
tagline: Module Lead
mobile: "+91 942-815-3422"
address: C-504,Meghansh Habitate,Jivraj Cross Road,B/H TV9 Office,Ahmedabad Pincode:380051
description: 'Module Lead having 8 Years Of experience

'
baseurl: 
objective: I am a creative thinker. I like to explore alternative solutions to problems
  and have an open mind about what will work best.
url: 
twitter_username: smit_shah_
github_username: smitshah81
linkedin_username: smitphpdeveloper
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
google_analytics: UA-102000946-1
